
- hosts: localhost
  connection: local
  sudo: yes
  tasks:
      - user: name=florian
              home=yes
              groups=docker
              shell=/usr/bin/zsh
              update_password=on_create
        ignore_errors: yes

      - lineinfile: dest=/etc/sudoers
                    state=present
                    line='florian ALL=(ALL) NOPASSWD:ALL'
                    validate='visudo -cf %s'

      - lineinfile: 'dest=/etc/pacman.conf line="{{ item }}"'
        with_items:
            - '[archlinuxfr]'
            - 'SigLevel = Never'
            - 'Server = http://repo.archlinux.fr/$arch'

      - pacman: update_cache=yes

      - pacman: name={{ item }}
        with_items:
            - xorg-xinit
            - yaourt
            - wget
            - git
            - tmux
            - gvim
            - thunderbird
            - nodejs
            - unzip
            - xsel
            - docker
            - pulseaudio
            - openssh
            - ctags
            - ruby
            - chromium
            - ntp

      - command: 'yaourt -S --noconfirm {{ item }}'
        sudo: no
        with_items:
            - vim-airline
            - python-powerline
        tags: [yaourt]

      - copy: src=files/getty@tty1.service
              dest=/etc/systemd/system/getty@tty1.service.d/override.conf
        tags: [login]

      - service: name={{ item }} enabled=yes state=started
        with_items:
            - dhcpcd
            - ntpd
        tags: [services]

      - copy: 'content="{{ public }}" dest=~/.ssh/id_rsa.pub mode=0600'
        sudo_user: florian
        when: public is defined

      - copy: 'content="{{ private }}" dest=~/.ssh/id_rsa mode=0600'
        sudo_user: florian
        when: private is defined

      - stat: path=~/dot-files
        register: dot-files
        sudo_user: florian

      - git: repo=git@github.com:docteurklein/dot-files.git dest=~/dot-files
        when: dot-files.stat.exists == True
        sudo_user: florian

      - shell: 'for f in $(ls -1 ~/dot-files); do ln -s ~/dot-files/$f ~/.$f; done'
        ignore_errors: yes
        sudo_user: florian

